### ISSUE TITLE
Can only set 'simple' charge modes

### ISSUE THREAD

**Issue by slankes** [a529987659852/openwbmqtt#14]
I am trying to set the charge mode. This works fine using:

```
service: openwbmqtt.change_global_charge_mode
data:
  mqtt_prefix: openWB
  global_charge_mode: "Stop"
```
but as soon as the charge mode has a "+" (Min+PV) or " " (Nur PV), the setting fails.
